name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'databasesubmissions'
          mysql root password: ''  
          mysql user: 'root'
          mysql password: '123456'
      - name: Setup Database 
        run: mysql use databasesubmissions;CREATE TABLE Doctors (name VARCHAR(255),department VARCHAR(255), id INT, PRIMARY KEY(id));CREATE TABLE Patients (name VARCHAR(255), id INT, PRIMARY KEY(id));CREATE TABLE DOC_PAT ( D_code INT, P_code INT, FOREIGN KEY (P_code) REFERENCES Patients(id),FOREIGN KEY (D_code) REFERENCES Doctors(id));
      - name: Run tests with pytest
        run: python -m unittest 
