name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python-rf
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'databasesubmissions'
          mysql root password: ''  
          mysql user: 'test'
          mysql password: '123456'
      - name: Setup Database 
        run: python setup.py
      - name: Run tests with python unittest
        run: python -m unittest 
