name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: databaseSubmissions
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python
      - name: Setup Database 
        run: python setup.py
      - name: Run tests with python unittest
        run: python -m unittest 
